/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BarbersIndexRouteImport } from './routes/barbers.index'
import { Route as ShopsSlugRouteImport } from './routes/shops.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as BookBarberIdRouteImport } from './routes/book.$barberId'
import { Route as BarbersBarberIdRouteImport } from './routes/barbers.$barberId'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedBarberRouteImport } from './routes/_authenticated/barber'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as BookingsBookingIdRescheduleRouteImport } from './routes/bookings.$bookingId.reschedule'
import { Route as BookShopShopSlugRouteImport } from './routes/book.shop.$shopSlug'
import { Route as AuthenticatedOwnerSupportRouteImport } from './routes/_authenticated/owner.support'
import { Route as AuthenticatedOwnerSettingsRouteImport } from './routes/_authenticated/owner.settings'
import { Route as AuthenticatedOwnerServicesRouteImport } from './routes/_authenticated/owner.services'
import { Route as AuthenticatedOwnerSalonRouteImport } from './routes/_authenticated/owner.salon'
import { Route as AuthenticatedOwnerReviewsRouteImport } from './routes/_authenticated/owner.reviews'
import { Route as AuthenticatedOwnerPortfolioRouteImport } from './routes/_authenticated/owner.portfolio'
import { Route as AuthenticatedOwnerCustomersRouteImport } from './routes/_authenticated/owner.customers'
import { Route as AuthenticatedOwnerCalendarRouteImport } from './routes/_authenticated/owner.calendar'
import { Route as AuthenticatedOwnerBookingsRouteImport } from './routes/_authenticated/owner.bookings'
import { Route as AuthenticatedOwnerBarbersRouteImport } from './routes/_authenticated/owner.barbers'
import { Route as AuthenticatedOwnerAnalyticsRouteImport } from './routes/_authenticated/owner.analytics'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as AuthenticatedAdminAccountHistoryRouteImport } from './routes/_authenticated/admin.account-history'
import { Route as AuthenticatedAdminSalonsIndexRouteImport } from './routes/_authenticated/admin.salons.index'
import { Route as AuthenticatedAdminOwnersIndexRouteImport } from './routes/_authenticated/admin.owners.index'
import { Route as AuthenticatedAdminCustomersIndexRouteImport } from './routes/_authenticated/admin.customers.index'
import { Route as AuthenticatedAdminBarbersIndexRouteImport } from './routes/_authenticated/admin.barbers.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAdminSalonsNewRouteImport } from './routes/_authenticated/admin.salons.new'
import { Route as AuthenticatedAdminSalonsIdRouteImport } from './routes/_authenticated/admin.salons.$id'
import { Route as AuthenticatedAdminOwnersNewRouteImport } from './routes/_authenticated/admin.owners.new'
import { Route as AuthenticatedAdminOwnersCodeRouteImport } from './routes/_authenticated/admin.owners.code'
import { Route as AuthenticatedAdminOwnersIdRouteImport } from './routes/_authenticated/admin.owners.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin.customers.$id'
import { Route as AuthenticatedAdminBarbersNewRouteImport } from './routes/_authenticated/admin.barbers.new'
import { Route as AuthenticatedAdminBarbersCodeRouteImport } from './routes/_authenticated/admin.barbers.code'
import { Route as AuthenticatedAdminBarbersIdRouteImport } from './routes/_authenticated/admin.barbers.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbersIndexRoute = BarbersIndexRouteImport.update({
  id: '/barbers/',
  path: '/barbers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/shops/$slug',
  path: '/shops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBarberIdRoute = BookBarberIdRouteImport.update({
  id: '/book/$barberId',
  path: '/book/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbersBarberIdRoute = BarbersBarberIdRouteImport.update({
  id: '/barbers/$barberId',
  path: '/barbers/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBarberRoute = AuthenticatedBarberRouteImport.update({
  id: '/barber',
  path: '/barber',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const BookingsBookingIdRescheduleRoute =
  BookingsBookingIdRescheduleRouteImport.update({
    id: '/reschedule',
    path: '/reschedule',
    getParentRoute: () => BookingsBookingIdRoute,
  } as any)
const BookShopShopSlugRoute = BookShopShopSlugRouteImport.update({
  id: '/book/shop/$shopSlug',
  path: '/book/shop/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerSupportRoute =
  AuthenticatedOwnerSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerSettingsRoute =
  AuthenticatedOwnerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerServicesRoute =
  AuthenticatedOwnerServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerSalonRoute = AuthenticatedOwnerSalonRouteImport.update({
  id: '/salon',
  path: '/salon',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerReviewsRoute =
  AuthenticatedOwnerReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerPortfolioRoute =
  AuthenticatedOwnerPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerCustomersRoute =
  AuthenticatedOwnerCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerCalendarRoute =
  AuthenticatedOwnerCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerBookingsRoute =
  AuthenticatedOwnerBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerBarbersRoute =
  AuthenticatedOwnerBarbersRouteImport.update({
    id: '/barbers',
    path: '/barbers',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerAnalyticsRoute =
  AuthenticatedOwnerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccountHistoryRoute =
  AuthenticatedAdminAccountHistoryRouteImport.update({
    id: '/account-history',
    path: '/account-history',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalonsIndexRoute =
  AuthenticatedAdminSalonsIndexRouteImport.update({
    id: '/salons/',
    path: '/salons/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOwnersIndexRoute =
  AuthenticatedAdminOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersIndexRoute =
  AuthenticatedAdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBarbersIndexRoute =
  AuthenticatedAdminBarbersIndexRouteImport.update({
    id: '/barbers/',
    path: '/barbers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSalonsNewRoute =
  AuthenticatedAdminSalonsNewRouteImport.update({
    id: '/salons/new',
    path: '/salons/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalonsIdRoute =
  AuthenticatedAdminSalonsIdRouteImport.update({
    id: '/salons/$id',
    path: '/salons/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOwnersNewRoute =
  AuthenticatedAdminOwnersNewRouteImport.update({
    id: '/owners/new',
    path: '/owners/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOwnersCodeRoute =
  AuthenticatedAdminOwnersCodeRouteImport.update({
    id: '/owners/code',
    path: '/owners/code',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOwnersIdRoute =
  AuthenticatedAdminOwnersIdRouteImport.update({
    id: '/owners/$id',
    path: '/owners/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBarbersNewRoute =
  AuthenticatedAdminBarbersNewRouteImport.update({
    id: '/barbers/new',
    path: '/barbers/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBarbersCodeRoute =
  AuthenticatedAdminBarbersCodeRouteImport.update({
    id: '/barbers/code',
    path: '/barbers/code',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBarbersIdRoute =
  AuthenticatedAdminBarbersIdRouteImport.update({
    id: '/barbers/$id',
    path: '/barbers/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/barber': typeof AuthenticatedBarberRoute
  '/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/barbers/$barberId': typeof BarbersBarberIdRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/barbers/': typeof BarbersIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/admin/account-history': typeof AuthenticatedAdminAccountHistoryRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/barbers': typeof AuthenticatedOwnerBarbersRoute
  '/owner/bookings': typeof AuthenticatedOwnerBookingsRoute
  '/owner/calendar': typeof AuthenticatedOwnerCalendarRoute
  '/owner/customers': typeof AuthenticatedOwnerCustomersRoute
  '/owner/portfolio': typeof AuthenticatedOwnerPortfolioRoute
  '/owner/reviews': typeof AuthenticatedOwnerReviewsRoute
  '/owner/salon': typeof AuthenticatedOwnerSalonRoute
  '/owner/services': typeof AuthenticatedOwnerServicesRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/support': typeof AuthenticatedOwnerSupportRoute
  '/book/shop/$shopSlug': typeof BookShopShopSlugRoute
  '/bookings/$bookingId/reschedule': typeof BookingsBookingIdRescheduleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/admin/barbers/$id': typeof AuthenticatedAdminBarbersIdRoute
  '/admin/barbers/code': typeof AuthenticatedAdminBarbersCodeRoute
  '/admin/barbers/new': typeof AuthenticatedAdminBarbersNewRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/owners/$id': typeof AuthenticatedAdminOwnersIdRoute
  '/admin/owners/code': typeof AuthenticatedAdminOwnersCodeRoute
  '/admin/owners/new': typeof AuthenticatedAdminOwnersNewRoute
  '/admin/salons/$id': typeof AuthenticatedAdminSalonsIdRoute
  '/admin/salons/new': typeof AuthenticatedAdminSalonsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/barbers/': typeof AuthenticatedAdminBarbersIndexRoute
  '/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/owners/': typeof AuthenticatedAdminOwnersIndexRoute
  '/admin/salons/': typeof AuthenticatedAdminSalonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/barber': typeof AuthenticatedBarberRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/barbers/$barberId': typeof BarbersBarberIdRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/barbers': typeof BarbersIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/admin/account-history': typeof AuthenticatedAdminAccountHistoryRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/barbers': typeof AuthenticatedOwnerBarbersRoute
  '/owner/bookings': typeof AuthenticatedOwnerBookingsRoute
  '/owner/calendar': typeof AuthenticatedOwnerCalendarRoute
  '/owner/customers': typeof AuthenticatedOwnerCustomersRoute
  '/owner/portfolio': typeof AuthenticatedOwnerPortfolioRoute
  '/owner/reviews': typeof AuthenticatedOwnerReviewsRoute
  '/owner/salon': typeof AuthenticatedOwnerSalonRoute
  '/owner/services': typeof AuthenticatedOwnerServicesRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/support': typeof AuthenticatedOwnerSupportRoute
  '/book/shop/$shopSlug': typeof BookShopShopSlugRoute
  '/bookings/$bookingId/reschedule': typeof BookingsBookingIdRescheduleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/admin/barbers/$id': typeof AuthenticatedAdminBarbersIdRoute
  '/admin/barbers/code': typeof AuthenticatedAdminBarbersCodeRoute
  '/admin/barbers/new': typeof AuthenticatedAdminBarbersNewRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/owners/$id': typeof AuthenticatedAdminOwnersIdRoute
  '/admin/owners/code': typeof AuthenticatedAdminOwnersCodeRoute
  '/admin/owners/new': typeof AuthenticatedAdminOwnersNewRoute
  '/admin/salons/$id': typeof AuthenticatedAdminSalonsIdRoute
  '/admin/salons/new': typeof AuthenticatedAdminSalonsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/barbers': typeof AuthenticatedAdminBarbersIndexRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/owners': typeof AuthenticatedAdminOwnersIndexRoute
  '/admin/salons': typeof AuthenticatedAdminSalonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/barber': typeof AuthenticatedBarberRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/barbers/$barberId': typeof BarbersBarberIdRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/barbers/': typeof BarbersIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/_authenticated/admin/account-history': typeof AuthenticatedAdminAccountHistoryRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/_authenticated/owner/barbers': typeof AuthenticatedOwnerBarbersRoute
  '/_authenticated/owner/bookings': typeof AuthenticatedOwnerBookingsRoute
  '/_authenticated/owner/calendar': typeof AuthenticatedOwnerCalendarRoute
  '/_authenticated/owner/customers': typeof AuthenticatedOwnerCustomersRoute
  '/_authenticated/owner/portfolio': typeof AuthenticatedOwnerPortfolioRoute
  '/_authenticated/owner/reviews': typeof AuthenticatedOwnerReviewsRoute
  '/_authenticated/owner/salon': typeof AuthenticatedOwnerSalonRoute
  '/_authenticated/owner/services': typeof AuthenticatedOwnerServicesRoute
  '/_authenticated/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/_authenticated/owner/support': typeof AuthenticatedOwnerSupportRoute
  '/book/shop/$shopSlug': typeof BookShopShopSlugRoute
  '/bookings/$bookingId/reschedule': typeof BookingsBookingIdRescheduleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/admin/barbers/$id': typeof AuthenticatedAdminBarbersIdRoute
  '/_authenticated/admin/barbers/code': typeof AuthenticatedAdminBarbersCodeRoute
  '/_authenticated/admin/barbers/new': typeof AuthenticatedAdminBarbersNewRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/owners/$id': typeof AuthenticatedAdminOwnersIdRoute
  '/_authenticated/admin/owners/code': typeof AuthenticatedAdminOwnersCodeRoute
  '/_authenticated/admin/owners/new': typeof AuthenticatedAdminOwnersNewRoute
  '/_authenticated/admin/salons/$id': typeof AuthenticatedAdminSalonsIdRoute
  '/_authenticated/admin/salons/new': typeof AuthenticatedAdminSalonsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/barbers/': typeof AuthenticatedAdminBarbersIndexRoute
  '/_authenticated/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/_authenticated/admin/owners/': typeof AuthenticatedAdminOwnersIndexRoute
  '/_authenticated/admin/salons/': typeof AuthenticatedAdminSalonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/admin'
    | '/barber'
    | '/owner'
    | '/profile'
    | '/settings'
    | '/barbers/$barberId'
    | '/book/$barberId'
    | '/bookings/$bookingId'
    | '/invite/$token'
    | '/shops/$slug'
    | '/barbers/'
    | '/bookings/'
    | '/favorites/'
    | '/admin/account-history'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/owner/analytics'
    | '/owner/barbers'
    | '/owner/bookings'
    | '/owner/calendar'
    | '/owner/customers'
    | '/owner/portfolio'
    | '/owner/reviews'
    | '/owner/salon'
    | '/owner/services'
    | '/owner/settings'
    | '/owner/support'
    | '/book/shop/$shopSlug'
    | '/bookings/$bookingId/reschedule'
    | '/admin/'
    | '/owner/'
    | '/admin/barbers/$id'
    | '/admin/barbers/code'
    | '/admin/barbers/new'
    | '/admin/customers/$id'
    | '/admin/owners/$id'
    | '/admin/owners/code'
    | '/admin/owners/new'
    | '/admin/salons/$id'
    | '/admin/salons/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/barbers/'
    | '/admin/customers/'
    | '/admin/owners/'
    | '/admin/salons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/barber'
    | '/profile'
    | '/settings'
    | '/barbers/$barberId'
    | '/book/$barberId'
    | '/bookings/$bookingId'
    | '/invite/$token'
    | '/shops/$slug'
    | '/barbers'
    | '/bookings'
    | '/favorites'
    | '/admin/account-history'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/owner/analytics'
    | '/owner/barbers'
    | '/owner/bookings'
    | '/owner/calendar'
    | '/owner/customers'
    | '/owner/portfolio'
    | '/owner/reviews'
    | '/owner/salon'
    | '/owner/services'
    | '/owner/settings'
    | '/owner/support'
    | '/book/shop/$shopSlug'
    | '/bookings/$bookingId/reschedule'
    | '/admin'
    | '/owner'
    | '/admin/barbers/$id'
    | '/admin/barbers/code'
    | '/admin/barbers/new'
    | '/admin/customers/$id'
    | '/admin/owners/$id'
    | '/admin/owners/code'
    | '/admin/owners/new'
    | '/admin/salons/$id'
    | '/admin/salons/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/barbers'
    | '/admin/customers'
    | '/admin/owners'
    | '/admin/salons'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/barber'
    | '/_authenticated/owner'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/barbers/$barberId'
    | '/book/$barberId'
    | '/bookings/$bookingId'
    | '/invite/$token'
    | '/shops/$slug'
    | '/barbers/'
    | '/bookings/'
    | '/favorites/'
    | '/_authenticated/admin/account-history'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/owner/analytics'
    | '/_authenticated/owner/barbers'
    | '/_authenticated/owner/bookings'
    | '/_authenticated/owner/calendar'
    | '/_authenticated/owner/customers'
    | '/_authenticated/owner/portfolio'
    | '/_authenticated/owner/reviews'
    | '/_authenticated/owner/salon'
    | '/_authenticated/owner/services'
    | '/_authenticated/owner/settings'
    | '/_authenticated/owner/support'
    | '/book/shop/$shopSlug'
    | '/bookings/$bookingId/reschedule'
    | '/_authenticated/admin/'
    | '/_authenticated/owner/'
    | '/_authenticated/admin/barbers/$id'
    | '/_authenticated/admin/barbers/code'
    | '/_authenticated/admin/barbers/new'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/owners/$id'
    | '/_authenticated/admin/owners/code'
    | '/_authenticated/admin/owners/new'
    | '/_authenticated/admin/salons/$id'
    | '/_authenticated/admin/salons/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/barbers/'
    | '/_authenticated/admin/customers/'
    | '/_authenticated/admin/owners/'
    | '/_authenticated/admin/salons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  BarbersBarberIdRoute: typeof BarbersBarberIdRoute
  BookBarberIdRoute: typeof BookBarberIdRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ShopsSlugRoute: typeof ShopsSlugRoute
  BarbersIndexRoute: typeof BarbersIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  BookShopShopSlugRoute: typeof BookShopShopSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbers/': {
      id: '/barbers/'
      path: '/barbers'
      fullPath: '/barbers/'
      preLoaderRoute: typeof BarbersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/shops/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$barberId': {
      id: '/book/$barberId'
      path: '/book/$barberId'
      fullPath: '/book/$barberId'
      preLoaderRoute: typeof BookBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbers/$barberId': {
      id: '/barbers/$barberId'
      path: '/barbers/$barberId'
      fullPath: '/barbers/$barberId'
      preLoaderRoute: typeof BarbersBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barber': {
      id: '/_authenticated/barber'
      path: '/barber'
      fullPath: '/barber'
      preLoaderRoute: typeof AuthenticatedBarberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/bookings/$bookingId/reschedule': {
      id: '/bookings/$bookingId/reschedule'
      path: '/reschedule'
      fullPath: '/bookings/$bookingId/reschedule'
      preLoaderRoute: typeof BookingsBookingIdRescheduleRouteImport
      parentRoute: typeof BookingsBookingIdRoute
    }
    '/book/shop/$shopSlug': {
      id: '/book/shop/$shopSlug'
      path: '/book/shop/$shopSlug'
      fullPath: '/book/shop/$shopSlug'
      preLoaderRoute: typeof BookShopShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner/support': {
      id: '/_authenticated/owner/support'
      path: '/support'
      fullPath: '/owner/support'
      preLoaderRoute: typeof AuthenticatedOwnerSupportRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/settings': {
      id: '/_authenticated/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof AuthenticatedOwnerSettingsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/services': {
      id: '/_authenticated/owner/services'
      path: '/services'
      fullPath: '/owner/services'
      preLoaderRoute: typeof AuthenticatedOwnerServicesRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/salon': {
      id: '/_authenticated/owner/salon'
      path: '/salon'
      fullPath: '/owner/salon'
      preLoaderRoute: typeof AuthenticatedOwnerSalonRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/reviews': {
      id: '/_authenticated/owner/reviews'
      path: '/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof AuthenticatedOwnerReviewsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/portfolio': {
      id: '/_authenticated/owner/portfolio'
      path: '/portfolio'
      fullPath: '/owner/portfolio'
      preLoaderRoute: typeof AuthenticatedOwnerPortfolioRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/customers': {
      id: '/_authenticated/owner/customers'
      path: '/customers'
      fullPath: '/owner/customers'
      preLoaderRoute: typeof AuthenticatedOwnerCustomersRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/calendar': {
      id: '/_authenticated/owner/calendar'
      path: '/calendar'
      fullPath: '/owner/calendar'
      preLoaderRoute: typeof AuthenticatedOwnerCalendarRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/bookings': {
      id: '/_authenticated/owner/bookings'
      path: '/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof AuthenticatedOwnerBookingsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/barbers': {
      id: '/_authenticated/owner/barbers'
      path: '/barbers'
      fullPath: '/owner/barbers'
      preLoaderRoute: typeof AuthenticatedOwnerBarbersRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/analytics': {
      id: '/_authenticated/owner/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof AuthenticatedOwnerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/account-history': {
      id: '/_authenticated/admin/account-history'
      path: '/account-history'
      fullPath: '/admin/account-history'
      preLoaderRoute: typeof AuthenticatedAdminAccountHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/salons/': {
      id: '/_authenticated/admin/salons/'
      path: '/salons'
      fullPath: '/admin/salons/'
      preLoaderRoute: typeof AuthenticatedAdminSalonsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/owners/': {
      id: '/_authenticated/admin/owners/'
      path: '/owners'
      fullPath: '/admin/owners/'
      preLoaderRoute: typeof AuthenticatedAdminOwnersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers/': {
      id: '/_authenticated/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/barbers/': {
      id: '/_authenticated/admin/barbers/'
      path: '/barbers'
      fullPath: '/admin/barbers/'
      preLoaderRoute: typeof AuthenticatedAdminBarbersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/salons/new': {
      id: '/_authenticated/admin/salons/new'
      path: '/salons/new'
      fullPath: '/admin/salons/new'
      preLoaderRoute: typeof AuthenticatedAdminSalonsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/salons/$id': {
      id: '/_authenticated/admin/salons/$id'
      path: '/salons/$id'
      fullPath: '/admin/salons/$id'
      preLoaderRoute: typeof AuthenticatedAdminSalonsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/owners/new': {
      id: '/_authenticated/admin/owners/new'
      path: '/owners/new'
      fullPath: '/admin/owners/new'
      preLoaderRoute: typeof AuthenticatedAdminOwnersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/owners/code': {
      id: '/_authenticated/admin/owners/code'
      path: '/owners/code'
      fullPath: '/admin/owners/code'
      preLoaderRoute: typeof AuthenticatedAdminOwnersCodeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/owners/$id': {
      id: '/_authenticated/admin/owners/$id'
      path: '/owners/$id'
      fullPath: '/admin/owners/$id'
      preLoaderRoute: typeof AuthenticatedAdminOwnersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/barbers/new': {
      id: '/_authenticated/admin/barbers/new'
      path: '/barbers/new'
      fullPath: '/admin/barbers/new'
      preLoaderRoute: typeof AuthenticatedAdminBarbersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/barbers/code': {
      id: '/_authenticated/admin/barbers/code'
      path: '/barbers/code'
      fullPath: '/admin/barbers/code'
      preLoaderRoute: typeof AuthenticatedAdminBarbersCodeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/barbers/$id': {
      id: '/_authenticated/admin/barbers/$id'
      path: '/barbers/$id'
      fullPath: '/admin/barbers/$id'
      preLoaderRoute: typeof AuthenticatedAdminBarbersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccountHistoryRoute: typeof AuthenticatedAdminAccountHistoryRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBarbersIdRoute: typeof AuthenticatedAdminBarbersIdRoute
  AuthenticatedAdminBarbersCodeRoute: typeof AuthenticatedAdminBarbersCodeRoute
  AuthenticatedAdminBarbersNewRoute: typeof AuthenticatedAdminBarbersNewRoute
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
  AuthenticatedAdminOwnersIdRoute: typeof AuthenticatedAdminOwnersIdRoute
  AuthenticatedAdminOwnersCodeRoute: typeof AuthenticatedAdminOwnersCodeRoute
  AuthenticatedAdminOwnersNewRoute: typeof AuthenticatedAdminOwnersNewRoute
  AuthenticatedAdminSalonsIdRoute: typeof AuthenticatedAdminSalonsIdRoute
  AuthenticatedAdminSalonsNewRoute: typeof AuthenticatedAdminSalonsNewRoute
  AuthenticatedAdminBarbersIndexRoute: typeof AuthenticatedAdminBarbersIndexRoute
  AuthenticatedAdminCustomersIndexRoute: typeof AuthenticatedAdminCustomersIndexRoute
  AuthenticatedAdminOwnersIndexRoute: typeof AuthenticatedAdminOwnersIndexRoute
  AuthenticatedAdminSalonsIndexRoute: typeof AuthenticatedAdminSalonsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccountHistoryRoute: AuthenticatedAdminAccountHistoryRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBarbersIdRoute: AuthenticatedAdminBarbersIdRoute,
  AuthenticatedAdminBarbersCodeRoute: AuthenticatedAdminBarbersCodeRoute,
  AuthenticatedAdminBarbersNewRoute: AuthenticatedAdminBarbersNewRoute,
  AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  AuthenticatedAdminOwnersIdRoute: AuthenticatedAdminOwnersIdRoute,
  AuthenticatedAdminOwnersCodeRoute: AuthenticatedAdminOwnersCodeRoute,
  AuthenticatedAdminOwnersNewRoute: AuthenticatedAdminOwnersNewRoute,
  AuthenticatedAdminSalonsIdRoute: AuthenticatedAdminSalonsIdRoute,
  AuthenticatedAdminSalonsNewRoute: AuthenticatedAdminSalonsNewRoute,
  AuthenticatedAdminBarbersIndexRoute: AuthenticatedAdminBarbersIndexRoute,
  AuthenticatedAdminCustomersIndexRoute: AuthenticatedAdminCustomersIndexRoute,
  AuthenticatedAdminOwnersIndexRoute: AuthenticatedAdminOwnersIndexRoute,
  AuthenticatedAdminSalonsIndexRoute: AuthenticatedAdminSalonsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedOwnerRouteChildren {
  AuthenticatedOwnerAnalyticsRoute: typeof AuthenticatedOwnerAnalyticsRoute
  AuthenticatedOwnerBarbersRoute: typeof AuthenticatedOwnerBarbersRoute
  AuthenticatedOwnerBookingsRoute: typeof AuthenticatedOwnerBookingsRoute
  AuthenticatedOwnerCalendarRoute: typeof AuthenticatedOwnerCalendarRoute
  AuthenticatedOwnerCustomersRoute: typeof AuthenticatedOwnerCustomersRoute
  AuthenticatedOwnerPortfolioRoute: typeof AuthenticatedOwnerPortfolioRoute
  AuthenticatedOwnerReviewsRoute: typeof AuthenticatedOwnerReviewsRoute
  AuthenticatedOwnerSalonRoute: typeof AuthenticatedOwnerSalonRoute
  AuthenticatedOwnerServicesRoute: typeof AuthenticatedOwnerServicesRoute
  AuthenticatedOwnerSettingsRoute: typeof AuthenticatedOwnerSettingsRoute
  AuthenticatedOwnerSupportRoute: typeof AuthenticatedOwnerSupportRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
}

const AuthenticatedOwnerRouteChildren: AuthenticatedOwnerRouteChildren = {
  AuthenticatedOwnerAnalyticsRoute: AuthenticatedOwnerAnalyticsRoute,
  AuthenticatedOwnerBarbersRoute: AuthenticatedOwnerBarbersRoute,
  AuthenticatedOwnerBookingsRoute: AuthenticatedOwnerBookingsRoute,
  AuthenticatedOwnerCalendarRoute: AuthenticatedOwnerCalendarRoute,
  AuthenticatedOwnerCustomersRoute: AuthenticatedOwnerCustomersRoute,
  AuthenticatedOwnerPortfolioRoute: AuthenticatedOwnerPortfolioRoute,
  AuthenticatedOwnerReviewsRoute: AuthenticatedOwnerReviewsRoute,
  AuthenticatedOwnerSalonRoute: AuthenticatedOwnerSalonRoute,
  AuthenticatedOwnerServicesRoute: AuthenticatedOwnerServicesRoute,
  AuthenticatedOwnerSettingsRoute: AuthenticatedOwnerSettingsRoute,
  AuthenticatedOwnerSupportRoute: AuthenticatedOwnerSupportRoute,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
}

const AuthenticatedOwnerRouteWithChildren =
  AuthenticatedOwnerRoute._addFileChildren(AuthenticatedOwnerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBarberRoute: typeof AuthenticatedBarberRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBarberRoute: AuthenticatedBarberRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BookingsBookingIdRouteChildren {
  BookingsBookingIdRescheduleRoute: typeof BookingsBookingIdRescheduleRoute
}

const BookingsBookingIdRouteChildren: BookingsBookingIdRouteChildren = {
  BookingsBookingIdRescheduleRoute: BookingsBookingIdRescheduleRoute,
}

const BookingsBookingIdRouteWithChildren =
  BookingsBookingIdRoute._addFileChildren(BookingsBookingIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  BarbersBarberIdRoute: BarbersBarberIdRoute,
  BookBarberIdRoute: BookBarberIdRoute,
  BookingsBookingIdRoute: BookingsBookingIdRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ShopsSlugRoute: ShopsSlugRoute,
  BarbersIndexRoute: BarbersIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  BookShopShopSlugRoute: BookShopShopSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
