/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BarbersIndexRouteImport } from './routes/barbers.index'
import { Route as ShopsSlugRouteImport } from './routes/shops.$slug'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as BookBarberIdRouteImport } from './routes/book.$barberId'
import { Route as BarbersBarberIdRouteImport } from './routes/barbers.$barberId'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as BookingsBookingIdRescheduleRouteImport } from './routes/bookings.$bookingId.reschedule'
import { Route as BookShopShopSlugRouteImport } from './routes/book.shop.$shopSlug'
import { Route as AuthenticatedAdminSalonsIndexRouteImport } from './routes/_authenticated/admin.salons.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAdminSalonsNewRouteImport } from './routes/_authenticated/admin.salons.new'
import { Route as AuthenticatedAdminSalonsIdRouteImport } from './routes/_authenticated/admin.salons.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbersIndexRoute = BarbersIndexRouteImport.update({
  id: '/barbers/',
  path: '/barbers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/shops/$slug',
  path: '/shops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBarberIdRoute = BookBarberIdRouteImport.update({
  id: '/book/$barberId',
  path: '/book/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbersBarberIdRoute = BarbersBarberIdRouteImport.update({
  id: '/barbers/$barberId',
  path: '/barbers/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const BookingsBookingIdRescheduleRoute =
  BookingsBookingIdRescheduleRouteImport.update({
    id: '/reschedule',
    path: '/reschedule',
    getParentRoute: () => BookingsBookingIdRoute,
  } as any)
const BookShopShopSlugRoute = BookShopShopSlugRouteImport.update({
  id: '/book/shop/$shopSlug',
  path: '/book/shop/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSalonsIndexRoute =
  AuthenticatedAdminSalonsIndexRouteImport.update({
    id: '/salons/',
    path: '/salons/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSalonsNewRoute =
  AuthenticatedAdminSalonsNewRouteImport.update({
    id: '/salons/new',
    path: '/salons/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalonsIdRoute =
  AuthenticatedAdminSalonsIdRouteImport.update({
    id: '/salons/$id',
    path: '/salons/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/barbers/$barberId': typeof BarbersBarberIdRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/shops/$slug': typeof ShopsSlugRoute
  '/barbers/': typeof BarbersIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/book/shop/$shopSlug': typeof BookShopShopSlugRoute
  '/bookings/$bookingId/reschedule': typeof BookingsBookingIdRescheduleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/salons/$id': typeof AuthenticatedAdminSalonsIdRoute
  '/admin/salons/new': typeof AuthenticatedAdminSalonsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/salons/': typeof AuthenticatedAdminSalonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/barbers/$barberId': typeof BarbersBarberIdRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/shops/$slug': typeof ShopsSlugRoute
  '/barbers': typeof BarbersIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/book/shop/$shopSlug': typeof BookShopShopSlugRoute
  '/bookings/$bookingId/reschedule': typeof BookingsBookingIdRescheduleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/salons/$id': typeof AuthenticatedAdminSalonsIdRoute
  '/admin/salons/new': typeof AuthenticatedAdminSalonsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/salons': typeof AuthenticatedAdminSalonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/barbers/$barberId': typeof BarbersBarberIdRoute
  '/book/$barberId': typeof BookBarberIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/shops/$slug': typeof ShopsSlugRoute
  '/barbers/': typeof BarbersIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/book/shop/$shopSlug': typeof BookShopShopSlugRoute
  '/bookings/$bookingId/reschedule': typeof BookingsBookingIdRescheduleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/salons/$id': typeof AuthenticatedAdminSalonsIdRoute
  '/_authenticated/admin/salons/new': typeof AuthenticatedAdminSalonsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/salons/': typeof AuthenticatedAdminSalonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/admin'
    | '/profile'
    | '/settings'
    | '/barbers/$barberId'
    | '/book/$barberId'
    | '/bookings/$bookingId'
    | '/shops/$slug'
    | '/barbers/'
    | '/bookings/'
    | '/favorites/'
    | '/book/shop/$shopSlug'
    | '/bookings/$bookingId/reschedule'
    | '/admin/'
    | '/admin/salons/$id'
    | '/admin/salons/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/salons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/profile'
    | '/settings'
    | '/barbers/$barberId'
    | '/book/$barberId'
    | '/bookings/$bookingId'
    | '/shops/$slug'
    | '/barbers'
    | '/bookings'
    | '/favorites'
    | '/book/shop/$shopSlug'
    | '/bookings/$bookingId/reschedule'
    | '/admin'
    | '/admin/salons/$id'
    | '/admin/salons/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/salons'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/barbers/$barberId'
    | '/book/$barberId'
    | '/bookings/$bookingId'
    | '/shops/$slug'
    | '/barbers/'
    | '/bookings/'
    | '/favorites/'
    | '/book/shop/$shopSlug'
    | '/bookings/$bookingId/reschedule'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/salons/$id'
    | '/_authenticated/admin/salons/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/salons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  BarbersBarberIdRoute: typeof BarbersBarberIdRoute
  BookBarberIdRoute: typeof BookBarberIdRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRouteWithChildren
  ShopsSlugRoute: typeof ShopsSlugRoute
  BarbersIndexRoute: typeof BarbersIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  BookShopShopSlugRoute: typeof BookShopShopSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbers/': {
      id: '/barbers/'
      path: '/barbers'
      fullPath: '/barbers/'
      preLoaderRoute: typeof BarbersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/shops/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$barberId': {
      id: '/book/$barberId'
      path: '/book/$barberId'
      fullPath: '/book/$barberId'
      preLoaderRoute: typeof BookBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbers/$barberId': {
      id: '/barbers/$barberId'
      path: '/barbers/$barberId'
      fullPath: '/barbers/$barberId'
      preLoaderRoute: typeof BarbersBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/bookings/$bookingId/reschedule': {
      id: '/bookings/$bookingId/reschedule'
      path: '/reschedule'
      fullPath: '/bookings/$bookingId/reschedule'
      preLoaderRoute: typeof BookingsBookingIdRescheduleRouteImport
      parentRoute: typeof BookingsBookingIdRoute
    }
    '/book/shop/$shopSlug': {
      id: '/book/shop/$shopSlug'
      path: '/book/shop/$shopSlug'
      fullPath: '/book/shop/$shopSlug'
      preLoaderRoute: typeof BookShopShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/salons/': {
      id: '/_authenticated/admin/salons/'
      path: '/salons'
      fullPath: '/admin/salons/'
      preLoaderRoute: typeof AuthenticatedAdminSalonsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/salons/new': {
      id: '/_authenticated/admin/salons/new'
      path: '/salons/new'
      fullPath: '/admin/salons/new'
      preLoaderRoute: typeof AuthenticatedAdminSalonsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/salons/$id': {
      id: '/_authenticated/admin/salons/$id'
      path: '/salons/$id'
      fullPath: '/admin/salons/$id'
      preLoaderRoute: typeof AuthenticatedAdminSalonsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminSalonsIdRoute: typeof AuthenticatedAdminSalonsIdRoute
  AuthenticatedAdminSalonsNewRoute: typeof AuthenticatedAdminSalonsNewRoute
  AuthenticatedAdminSalonsIndexRoute: typeof AuthenticatedAdminSalonsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminSalonsIdRoute: AuthenticatedAdminSalonsIdRoute,
  AuthenticatedAdminSalonsNewRoute: AuthenticatedAdminSalonsNewRoute,
  AuthenticatedAdminSalonsIndexRoute: AuthenticatedAdminSalonsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BookingsBookingIdRouteChildren {
  BookingsBookingIdRescheduleRoute: typeof BookingsBookingIdRescheduleRoute
}

const BookingsBookingIdRouteChildren: BookingsBookingIdRouteChildren = {
  BookingsBookingIdRescheduleRoute: BookingsBookingIdRescheduleRoute,
}

const BookingsBookingIdRouteWithChildren =
  BookingsBookingIdRoute._addFileChildren(BookingsBookingIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  BarbersBarberIdRoute: BarbersBarberIdRoute,
  BookBarberIdRoute: BookBarberIdRoute,
  BookingsBookingIdRoute: BookingsBookingIdRouteWithChildren,
  ShopsSlugRoute: ShopsSlugRoute,
  BarbersIndexRoute: BarbersIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  BookShopShopSlugRoute: BookShopShopSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
